Improve anonymization scripts
coopengo/coog-docker pull request #10
Opened 2021-09-16 12:38 UTC by mpaulmier

Fix #20864

2021-09-16 12:53 UTC, jmousset requested changes

2021-09-16 12:53 UTC, jmousset commented on scripts/anonymize_recette.sql
> +    update res_user set login = md5(login) where login != 'admin';
on veut pas faire ça pour les user du groupe "ne pas anonymiser".

2021-09-16 13:18 UTC, mpaulmier commented on scripts/anonymize_recette.sql
> +    update res_user set login = md5(login) where login != 'admin';
Done

2021-09-16 14:01 UTC, jmousset commented on scripts/README.md
> +psql -U <nom_de_l'utilisateur> -d <nom_de_la_copie> 2>&1 /dev/null << cat anonymize_recette.sql
anonymize_coog_db.sql ?

2021-09-16 14:02 UTC, jmousset commented on scripts/README.md
> +psql -U <nom_de_l'utilisateur> -d <nom_de_la_copie> 2>&1 /dev/null << cat anonymize_recette.sql
il faut mettre ça à place du pavé existant qui parle d'anonymisation (et qui est deprecated )

2021-09-16 14:13 UTC, JCavallo requested changes
@mpaulmier Il faudrait plutôt faire la PR sur la branche swarm :(

2021-09-16 14:23 UTC, fabienmoreaucoopengo submitted a review, later dismissed

2021-09-16 14:55 UTC, jmousset commented on README.md
> +To anonymize a database, download use the file `anonymize_coog_db.sql` in the `bin/resources/` folder and use the following script replacing the values between `<>`:
typo: download use

2021-09-16 15:02 UTC, mpaulmier commented on README.md
> +To anonymize a database, download use the file `anonymize_coog_db.sql` in the `bin/resources/` folder and use the following script replacing the values between `<>`:
Merci, done

2021-09-16 15:05 UTC, jmousset approved these changes

2021-09-16 15:21 UTC, JCavallo commented on bin/resources/anonymize_coog_db.sql
> +    update res_user set password_hash = '$pbkdf2-sha512$25000$9J7T2rtXKiUE4PwfY.x9Tw$Of5naHuwI71tuLLZluyq0dA.X4yq5fewhDImuzaDkVYnmAHKeIyLvOqLIgWB34m5SlFHOCyQd9CHD9ISQ/TE9g' where login = 'admin';
Ca mériterait un commentaire :)

2021-09-16 15:21 UTC, JCavallo commented on README.md
> +    dropdb -e -U $PG_USER $COPY
Pourquoi tu as viré ce que j'avais mis ? Il y a des branchements faits dans manage_db pour que ça soit facile à faire, et qu'un user pas trop expérimenté puisse se débrouiller :'(

2021-09-16 15:24 UTC, jmousset commented on README.md
> +    dropdb -e -U $PG_USER $COPY
@JCavallo c'est moi qui lui ai dit virer ces histoire de niveau, pas utilisé. pour n'avoir qu'un seul script à utiliser, et avoir juste des var à éditer au début pour chipoter ( demande de romain pour la gestion via variable dans le script)

2021-09-16 15:24 UTC, mpaulmier commented on env_files/var.env
> +TRYTOND_DATABASE__PATH=/workspace/io/edm
Tu es sur une version ancienne de la PR, je l'ai supprimé

2021-09-16 16:10 UTC, mpaulmier commented on README.md
> +    dropdb -e -U $PG_USER $COPY
@JCavallo On n'avait pas connaissance manage_db, j'aurai dû aller jeter un oeil, j'ai modifié la fonction `anonymize` et restore le README (modulo les niveau)

2021-09-16 16:17 UTC, jmousset approved these changes

2021-09-17 08:19 UTC, jmousset commented on bin/resources/anonymize_coog_db.sql
> +-- The following variables will not be taken into account if the company is subscribed to a contract
@mpaulmier ce serait possible de mettre ce bloc déclaraion de variable au tout début du script ?

2021-09-17 08:34 UTC, mpaulmier commented on bin/resources/anonymize_coog_db.sql
> +-- The following variables will not be taken into account if the company is subscribed to a contract
J'ai déplacé la fonction en haut du fichier, plpgsql ne permet pas forcément de faire ça proprement de ce que j'en sais.

2021-09-17 09:33 UTC, JCavallo approved these changes
Je repasserai probablement dessus pour variabiliser, mais ok pour l'instant

2021-09-17 09:41 UTC, merged