Anonymization now doesnt change login for users in group Coog Dot not anonymize
coopengo/coog-docker pull request #45
Opened 2022-12-12 11:29 UTC by SylvainEmonet

Fix #PROCK-114

Report to 2.10

2022-12-12 14:16 UTC, sleibo-coopengo commented on CHANGELOG_FR
> +* BUG#PROCK-114 Le script d'anonymisation ne doit plus changer le login des users dans le groupe Coog A ne pas anonymiser
Typo sur "anonymiser"

2022-12-12 14:16 UTC, sleibo-coopengo submitted a review, later dismissed

2022-12-12 15:02 UTC, SylvainEmonet commented on README.md
> +A group of users in Coog named 'Coog Do Not Anonimyze' allow maintainers to
```suggestion
A group of users in Coog named 'Coog Do Not Anonymize' allow maintainers to
```

2022-12-12 15:02 UTC, SylvainEmonet commented on CHANGELOG_FR
> +* BUG#PROCK-114 Le script d'anonymisation ne doit plus changer le login des users dans le groupe Coog A ne pas anonymiser
je ne vois pas le problème, tu peux faire une suggestion stp ?

2022-12-13 09:19 UTC, mpaulmier approved these changes

2022-12-13 10:09 UTC, JCavallo requested changes

2022-12-13 10:09 UTC, JCavallo commented on bin/resources/anonymize_coog_db.sql
> +    PERFORM anon_table('res_user', 'name, login', 'email', 'id: not in :(select id from res_user where login = ''admin'');id: not in :(select "user" from "res_user-res_group" where "group" in (select
Quasiment sûr qu'il manque des `'` quelque part

2022-12-13 10:11 UTC, JCavallo approved these changes
My bad

2022-12-13 14:22 UTC, merged